project: 
  type: website
  output-dir: _site
 
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default
  
website: 
  page-navigation: true
  title: "PO.DAAC Cookbook" 
  site-url: "https://podaac.github.io/tutorials/" 
  repo-url: https://github.com/podaac/tutorials
  repo-actions: [issue] #wanted to add edit & source, but since our repo has a "master" branch instead of a "main" branch, edit & source will not work.
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; PO.DAAC, 2022"
    
  sidebar:
    logo: "images/podaac-logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://podaac.jpl.nasa.gov/
        text: "PO.DAAC Website"
      - icon: github
        href: https://github.com/podaac/tutorials
        text: "Github Repository"        
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Welcome"
      - text: "Cheatsheets & Guides" 
        href: quarto_text/cheatsheet.qmd 
      - section: quarto_text/HowTo.qmd 
        contents: 
          - section: "Find Data"
            contents:
              - text: "using Earthdata Search"
                href: external/earthdata_search.md
              - text: "using Code"
                href: external/find_data_programmatically.qmd
          - text: "Authenticate"
            href: external/NASA_Earthdata_Authentication.ipynb 
          - section: "Access Data"
            contents: 
              - text: "in the Cloud"
                href: external/access-cloud-python.ipynb
              - text: "Locally"
                href: external/access-local-python.ipynb
              - text: "via OPeNDAP"
                href: external/access-local-opendap.qmd
          - text: "Read Data"
            href: external/read_data.qmd
          - text: "Download/Subscribe"
            href: quarto_text/DataSubscriberDownloader.qmd
      - section: quarto_text/Tutorials.qmd 
        contents:
          - section: quarto_text/DatasetSpecificExamples.qmd
            contents:
              - section: quarto_text/ECCO.qmd
                contents:
                  - text: "In-cloud Access"
                    href: external/ECCO_cloud_direct_access_s3.ipynb
                  - text: "Local Download Access"
                    href: external/ECCO_download_data.ipynb
                  - text: "Use Case Demo" 
                    href: notebooks/meetings_workshops/workshop_osm_2022/ECCO_ssh_sst_corr.ipynb
              - section: quarto_text/GHRSST.qmd
                contents:
                  - text: "Use Case Demo"
                    href: notebooks/datasets/enso_MUR_tutorial_final.ipynb
                  - text: "MUR with Dask"
                    href: notebooks/Advanced_cloud/basic_dask.ipynb
                  - text: "In QGIS"
                    href: notebooks/GIS/MUR_SSTA_QGIS.md  
                  - text: "OPeNDAP Access"
                    href: notebooks/opendap/MUR-OPeNDAP.ipynb
                  - text: "In-Cloud Access"
                    href: notebooks/datasets/MUR_SST_Washington_Comparison.ipynb
              - section: quarto_text/OPERA.qmd
                contents:
                  - section: "Visualization and Mosaicking"
                    contents:
                      - text: "Cloud"
                        href: notebooks/datasets/OPERA_GIS_Cloud.ipynb
                      - text: "Local"
                        href: notebooks/datasets/OPERA_GIS_Notebook.ipynb
              - section:  quarto_text/Sentinel6MF.qmd
                contents: 
                  - text: "Access by Cycle/Pass"
                    href: notebooks/sentinel-6/Access_Sentinel6_By_CyclePass.ipynb               
                  - text: "Access NRT Data"
                    href: notebooks/sentinel-6/Access_Sentinel6_NRT.ipynb              
                  - text: "OPeNDAP Access"
                    href: notebooks/meetings_workshops/workshop_osm_2022/S6_OPeNDAP_Access_Gridding.ipynb
              - section: quarto_text/SMAP.qmd
                contents:
                  - text: "Use Case Demo"
                    href: notebooks/datasets/smap_imerg_tutorial.ipynb
              - section: quarto_text/SMODE.qmd
                contents:
                  - text: "Case Study Airborne Part 1"
                    href: external/DownloadDopplerScattData.ipynb
                  - text: "Case Study Airborne Part 2"
                    href: external/VisualizeDopplerScattData.ipynb
                  - text: "Case Study In Situ"
                    href: external/insitu_dataviz_demo.ipynb
              - section: quarto_text/SWOT.qmd
                contents:
                  - section: "Search"
                    contents:
                      - text: "via GUI"
                        href: quarto_text/SWOT.html#via-graphical-user-interface
                      - text: "Programmatically"
                        href: quarto_text/SWOT.html#programmatically-ie.-within-python-code-workflows
                      - text: "via Command Line"
                        href: quarto_text/SWOT.html#via-command-line---po.daac-subscriberdownloader-examples
                      - text: "Spatial Coverage"
                        href: quarto_text/SWOT.html#swot-spatial-coverage-for-beta-pre-validated-products-v1.1
                      - text: "Tips for SWOT HR Spatial Search"
                        href: quarto_text/SWOT.html#tips-for-swot-hr-spatial-search
                  - section: "Access & Visualization"
                    contents:
                      - section: "SWOT Hydrology Dataset Overview"
                        contents: 
                          - text: "Cloud"
                            href: notebooks/datasets/SWOTHR_s3Access_real_data_v11.ipynb
                          - text: "Local"
                            href: notebooks/datasets/SWOTHR_localmachine_real_data_v11.ipynb
                      - section: "Raster Multifile"
                        contents:
                          - text: "Cloud"
                            href: notebooks/GIS/SWOT_Raster_Notebook_cloud.ipynb
                          - text: "Local"
                            href: notebooks/GIS/SWOT_Raster_Notebook_local.ipynb
                      - section: "SWOT Oceanography"
                        contents: 
                          - text: "Cloud"
                            href: notebooks/datasets/DirectCloud_Access_SWOT_Oceanography.ipynb
                          - text: "Local"
                            href: notebooks/datasets/Localmachine_SWOT_Oceanography.ipynb
                  - section: "GIS Workflows"
                    contents:
                      - text: "StoryMap"
                        href: https://storymaps.arcgis.com/stories/4a9184e813e540248040069580f6a54c
                      - text: "Shapefile Exploration"
                        href: notebooks/GIS/SWOT_GISshapefiles.ipynb
                      - text: "Datetime Conversion"
                        href: notebooks/GIS/SWOT_datetime_GIS.ipynb
                  - section: "Transform Data"
                    contents:
                      - text: "Hydrology Time Series"
                        href: notebooks/GIS/SWOTshp_CSVconversion.ipynb
                      - section: "NetCDF to Geotiff"
                        contents:
                          - text: "Mac/Linux"
                            href: notebooks/GIS/Subscriber_nc_to_tif_SWOT.qmd
                          - text: "Windows"
                            href: notebooks/GIS/GDAL_NetCDF_GeoTIFF.ipynb
          - href: quarto_text/GIS.qmd 
            text: "GIS"
          - section: quarto_text/CloudvsLocalWorkflows.qmd
            contents:
              - section: "Estuary Example"
                contents:
                  - text: "Cloud"
                    href: notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb
                  - text: "Local"
                    href: notebooks/meetings_workshops/workshop_osm_2022/Cloud_DirectDownload_AmazonRiver_Estuary_Exploration.ipynb
              - section: "Reservoir Example"
                contents:
                  - text: "Cloud"
                    href: notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Cloud.ipynb
                  - text: "Local"
                    href: notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Local.ipynb
              - section: "Lake Extent Example"
                contents:
                  - text: "Cloud"
                    href: notebooks/datasets/OPERA_GIS_Cloud.ipynb
                  - text: "Local"
                    href: notebooks/datasets/OPERA_GIS_Notebook.ipynb
          - section: quarto_text/ScienceDataStories.qmd
            contents:
              - section: "Amazon Estuary Exploration"
                contents:
                  - text: "Cloud"
                    href: notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb
                  - text: "Local"
                    href: notebooks/meetings_workshops/workshop_osm_2022/Cloud_DirectDownload_AmazonRiver_Estuary_Exploration.ipynb
              - text: "Monthly SST EOF Decomposition"
                href: notebooks/DataStories/eof_example_ersst.ipynb
              - text: "SSS Changes in the Arctic"
                href: notebooks/meetings_workshops/arctic_2019.ipynb 
              - text: "Mississippi River Heights"
                href: notebooks/meetings_workshops/swot_ea_hackweek_2022/River_Heights_in_the_Cloud.ipynb
              - text: "SST Cross Validation"
                href: notebooks/SWOT-EA-2021/Colocate_satellite_insitu_ocean.ipynb
          - section: quarto_text/CloudOptimizedExamples.qmd
            contents: 
              - text: "Zarr Access for NetCDF4 Files"
                href: external/zarr_access.ipynb
              - text: "zarr-eosdis-store library"
                href: external/zarr-eosdis-store.ipynb
              - text: "zarr2netCDF" 
                href: external/cof-zarr-reformat.ipynb
      - section: quarto_text/Advanced.qmd
        contents: 
          - section: notebooks/aws_lambda_sst/docs/documentation.md
            contents:
              - text: "Notebook"
                href: notebooks/aws_lambda_sst/podaac-lambda-invoke-sst-global-mean.ipynb
          - text: "Dask"
            href: notebooks/Advanced_cloud/basic_dask.ipynb
          - text: "Kerchunk"
            href: external/SWOT_to_kerchunk.ipynb
          - text: "Dask, Kerchunk, & Zarr"
            href: external/SWOT_SSH_dashboard.ipynb
      - href: quarto_text/Experimental.qmd
        text: "In Development"
      - href: quarto_text/Workshops.qmd
        text: "Workshops"
      - section: quarto_text/Webinars.qmd
        contents:
          - text: "July 2022 Earthdata Webinar Notebook"
            href: external/July_2022_Earthdata_Webinar.ipynb
      - href: quarto_text/TechGuides.qmd
        text: "Tech Guides"
      - section: quarto_text/Contribute.qmd
        contents: 
          - text: "Tutorial Template"
            href: notebooks/Tutorials_TEMPLATE.ipynb
      - href: quarto_text/Questions.qmd
        text: "Questions?"

format:
  html:
    include-in-header: gtm_code_head.html
    include-before-body: gtm_code_body.html
    theme:
      light: cosmo # from https://quarto.org/docs/output-formats/html-themes.html
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
