project: 
  type: website
  output-dir: _site
 
execute:
  freeze: true  # never re-execute computational content during project render, needed for .qmd and .rmd since quarto does not render .ipynb by default
  
website: 
  page-navigation: true
  title: "PO.DAAC Cookbook" 
  site-url: "https://podaac.github.io/tutorials/" 
  repo-url: https://github.com/podaac/tutorials
  repo-actions: [edit, issue]
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; PO.DAAC, 2022"
    
  sidebar:
    logo: "images/podaac-logo.png"
    pinned: true
    align: center
    tools: 
      - icon: globe
        href: https://podaac.jpl.nasa.gov/
        text: "PO.DAAC Website"
      - icon: github
        href: https://github.com/podaac/tutorials
        text: "Github Repository"        
    
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: "Welcome"
      - text: "Cheatsheets & Guides" 
        href: quarto_text/cheatsheet.qmd 
      - section: quarto_text/HowTo.qmd 
        contents: 
          - text: "Search"
            href: external/earthdata_search.md
          - text: "Authenticate"
            href: external/NASA_Earthdata_Authentication.ipynb 
          - text: "Access in Cloud"
            href: external/Direct_S3_Access_NetCDF.ipynb 
          - text: "Download/Subscribe"
            href: quarto_text/DataSubscriberDownloader.qmd
      - section: quarto_text/Tutorials.qmd 
        contents:
          - section: quarto_text/DatasetSpecificExamples.qmd
            contents:
              - section: quarto_text/ECCO.qmd
                contents:
                  - text: "In-cloud Access"
                    href: external/ECCO_cloud_direct_access_s3.ipynb
                  - text: "Local Download Access"
                    href: external/ECCO_download_data.ipynb
                  - text: "Use Case Demo" 
                    href: notebooks/meetings_workshops/workshop_osm_2022/ECCO_ssh_sst_corr.ipynb
              - section:  quarto_text/Sentinel6MF.qmd
                contents: 
                  - text: "Access by Cycle/Pass"
                    href: notebooks/sentinel-6/Access_Sentinel6_By_CyclePass.ipynb               
                  - text: "Access NRT Data"
                    href: notebooks/sentinel-6/Access_Sentinel6_NRT.ipynb              
                  - text: "OPeNDAP Access"
                    href: notebooks/meetings_workshops/workshop_osm_2022/S6_OPeNDAP_Access_Gridding.ipynb
              - section: quarto_text/SMAP.qmd
                contents:
                  - text: "Use Case Demo"
                    href: notebooks/datasets/smap_imerg_tutorial.ipynb
              - section: quarto_text/SMODE.qmd
                contents:
                  - text: "Case Study Airborne Part 1"
                    href: external/DownloadDopplerScattData.ipynb
                  - text: "Case Study Airborne Part 2"
                    href: external/VisualizeDopplerScattData.ipynb
                  - text: "Case Study In Situ"
                    href: external/insitu_dataviz_demo.ipynb
              - section: quarto_text/SWOT.qmd
                contents:
                  - section: "Search"
                    contents:
                      - text: "Programmatically"
                        href: notebooks/SearchDownload_SWOTviaCMR.ipynb
                      - text: "By SWORD ID"
                        href: notebooks/SWORD_River_Demo.ipynb
                      - text: "By HUC ID"
                        href: notebooks/HUC Feature Translation Service Examples-updated-20210804.ipynb
                  - section: "In-cloud Access"
                    contents:
                      - text: "Sample SWOT Hydrology Data"
                        href: notebooks/meetings_workshops/swot_ea_workshop_sept2022/SWOTHR_s3Access.ipynb
                      - text: "Sample SWOT Oceanography Data"
                        href: external/Direct_Access_SWOT_sim_Oceanography.ipynb
                  - section: "GIS Workflows"
                    contents:
                      - text: "GIS HR Shapefile Exploration"
                        href: notebooks/GIS/SWOTsample_GISshapefiles.ipynb
                      - text: "NetCDF to Geotiff"
                        href: notebooks/GIS/Subscriber_nc_to_tif_SWOT.qmd
                  - section: "Transform Data"
                    contents:
                      - text: "Hydrology Time Series"
                        href: notebooks/GIS/SWOTsample_CSVconversion.ipynb
                      - text: "Subset by Bounding Box"
                        href: 
          - href: quarto_text/GIS.qmd 
            text: "GIS"
          - section: quarto_text/CloudvsLocalWorkflows.qmd
            contents:
              - section: "Estuary Example"
                contents:
                  - text: "Cloud"
                    href: notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb
                  - text: "Local"
                    href: notebooks/meetings_workshops/workshop_osm_2022/Cloud_DirectDownload_AmazonRiver_Estuary_Exploration.ipynb
              - section: "Reservoir Example"
                contents:
                  - text: "Cloud"
                    href: notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Cloud.ipynb
                  - text: "Local"
                    href: notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Local.ipynb
          - section: quarto_text/PairingCloudNoncloudData.qmd
            contents:
              - text: "River Heights Comparison"
                href: notebooks/meetings_workshops/swot_ea_hackweek_2022/River_Heights_in_the_Cloud.ipynb
              - text: "Ocean Satellite & In-situ Comparison"
                href: notebooks/SWOT-EA-2021/Colocate_satellite_insitu_ocean.ipynb
          - section: quarto_text/CloudOptimizedExamples.qmd
            contents: 
              - text: "Zarr Access for NetCDF4 Files"
                href: external/zarr_access.ipynb
              - text: "zarr-eosdis-store library"
                href: external/zarr-eosdis-store.ipynb
              - text: "zarr2netCDF" 
                href: external/cof-zarr-reformat.ipynb
      - href: quarto_text/Experimental.qmd
        text: "In Development"
      - href: quarto_text/Workshops.qmd
        text: "Workshops"
      - section: quarto_text/Webinars.qmd
        contents:
          - text: "July 2022 Earthdata Webinar Notebook"
            href: external/July_2022_Earthdata_Webinar.ipynb
      - href: quarto_text/TechGuides.qmd
        text: "Tech Guides"
      - section: quarto_text/Contribute.qmd
        contents: 
          - text: "Tutorial Template"
            href: notebooks/Tutorials_TEMPLATE.ipynb
      - href: quarto_text/Questions.qmd
        text: "Questions?"

format:
  html:
    theme:
      light: cosmo # from https://quarto.org/docs/output-formats/html-themes.html
      dark: darkly
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
