---
title: Cloud Optimized Data Formats
subtitle: Faster data access when working in the cloud
---

Traditional Earth data formats like netCDF and HDF are not optimal for storing and then accessing those data in the cloud, e.g. for streaming data from the files rather than direct downloading. They do work, but new file formats are emerging that allow faster data access. Some of the future data sets hosted at PO.DAAC could be in these new formats, such as [Zarr](https://guide.cloudnativegeo.org/zarr/intro.html) (no netCDF, HDF available). In other cases, technology is emerging that allows data sets to remain in traditional formats, but with supplementary files which act as "road maps" to the data, allowing machines/software to navigate the data files more efficiently. Regardless of which method is implemented, a key goal is to minimize the additional technical knowledge a user must have to access the data. For example, the Python package `Xarray` is adding new capabilities to its `open_dataset()` function so it works in a similar way for either netCDF or cloud optimized data. There are many resources to gain a high-level understanding of cloud optimized data, such as this page [Cloud-Optimized Geospatial Formats Guide](https://guide.cloudnativegeo.org). Additionaly, the notebooks in this section often provide additional resources for learning. 

### **Zarr** 
- [Tutorial for NetCDF4 Files](../external/zarr_access.ipynb) - Teaches about the Zarr cloud optimized format

### **Kerchunk and Virtualizarr**
Both [Kerchunk](https://fsspec.github.io/kerchunk/) and [Virtualizarr](https://virtualizarr.readthedocs.io/en/latest/) are Python packages that aim to achieve cloud-optimized results while still allowing a data set to be stored in traditional formats (e.g. netCDF, HDF). These packages create relatively small supplementary files that can be used by software to more efficiently navigate through a collection of e.g. netCDF files. This allows much faster lazy loading, faster selection and access to subsets of the data, and in some cases faster computations. 

- [VirtualiZarr recipes](../notebooks/Advanced_cloud/virtualizarr_recipes.ipynb) - Meant to be used after having a high-level understanding of the pacakge, this notebook goes through several functionalities of VirtualiZarr that we found relevant to Earthdata users. Workflows here combine VirtualiZarr with the earthaccess package.
- [Kerchunk recipes](../notebooks/Advanced_cloud/kerchunk_recipes.ipynb) - Meant to be used after having a high-level understanding of the pacakge, this notebook goes through several functionalities of kerchunk that we found relevant to Earthdata users. Workflows here combine Kerchunk with the earthaccess package.
- [Kerchunk JSON Generation](../external/SWOT_to_kerchunk.ipynb) - An additional tutorial on generating a Kerchunk JSON file, demonstrating its use with one of the SWOT data sets hosted on PO.DAAC. Creates output for input in the following tutorial.
- [Integrating Dask, Kerchunk, Zarr and Xarray](../external/SWOT_SSH_dashboard.ipynb) - Efficiently visualize a whole collection of data in an interactive dashboard via cloud-optimized formats.
- Virtualizarr (coming soon)