---
title: Cloud Optimized Examples
---

Tutorials highlighting Cloud Optimized Formats.

### Example: Zarr Access for NetCDF4 Files

This tutorial teaches about the Zarr format and library for accessing data in the cloud, building on prior knowledge from CMR and Earthdata Login tutorials, working through an example of using the EOSDIS Zarr Store to access data using XArray.

[Zarr Hackathon Tutorial](../external/zarr_access.ipynb)

### Example: Zarr Dataset

This tutorial opens PO.DAAC MUR dataset in a zarr format.

[Zarr-eosdid-store Library](../external/zarr-eosdis-store.ipynb)

### Example: Opening NetCDF's in Zarr Format

This tutorial leverages the Zarr reformatter service (available through Harmony API) to access ocean bottom pressure (OBP) data from ECCO V4r4 in Zarr format (instead of native netCDF4 file format).

[Zarr2netCDF Example](../external/cof-zarr-reformat.ipynb)


## Additional Resources
- [Cloud Optimized Geospatial Formats Guide](https://developmentseed.org/cloud-optimized-geospatial-formats-guide/) - Methods for Generating and Testing Cloud-Optimized Geospatial Formats