---
title: Cloud vs. Local Workflows
---

Tutorials showcasing the same workflows in in different locations: in the cloud hosted by Amazon Web Services (AWS) or on a local machine downloaded from the cloud. 

Note: NASA Earthdata is hosted in the `us-west-2` region in the cloud.

### Examples: SWOT Oceanography & Hydrology Data Exploration

Access SWOT Hydrology data [Cloud Version](../notebooks/datasets/SWOTHR_s3Access.ipynb) | [Local Version](../notebooks/datasets/SWOTHR_localmachine.ipynb)

Access SWOT Oceanography data [Cloud Version](../notebooks/datasets/DirectCloud_Access_SWOT_Oceanography.ipynb) | [Local Version](../notebooks/datasets/Localmachine_SWOT_Oceanography.ipynb)

SWOT Raster Multifile Access & Quality Flag Application [Cloud Version](../notebooks/datasets/SWOT_Raster_Notebook_cloud.ipynb) | [Local Version](../notebooks/datasets/SWOT_Raster_Notebook_local.ipynb)

### Example: Amazon Estuary Exploration

These tutorials explore the relationships between land water equivalent thickness, river height, sea surface salinity, and sea surface temperature in the Amazon River estuary and coastal region from multiple datasets (GRACE-FO, Pre-SWOT MEaSUREs, OISSS, & MODIS).

[Cloud Version](../notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb) | [Local Version](../notebooks/meetings_workshops/workshop_osm_2022/Cloud_DirectDownload_AmazonRiver_Estuary_Exploration.ipynb)

### Example: Lake Extent

These tutorials explore OPERA Dynamic Surface Water Extent (DSWx) product: how to search for, access, visualize, and mosaic OPERA data over lake Powell.

[Cloud Version](../notebooks/datasets/OPERA_GIS_Cloud.ipynb) | [Local Version](../notebooks/datasets/OPERA_GIS_Notebook.ipynb)

### Example: Reservoir Surface Area

These tutorials estimate reservoir surface area from Harmonized Landsat-Sentinel (HLS) Imagery.

[Cloud Version](../notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Cloud.ipynb) | [Local Version](../notebooks/meetings_workshops/swot_ea_hackweek_2022/HLS-WaterDetection-Local.ipynb)

