---
title: Contribute
---

## Make Suggestions or Add Tutorials!

These instructions are for anyone that would like to contribute tutorials that utilize (in part) NASA Earthdata to the PO.DAAC Cookbook. If you have [cloned the PO.DAAC tutorials GitHub repository](TechGuides.qmd#cloning-this-github-repository) with all of the PO.DAAC Cookbook Notebooks, you can make changes on your copy of the tutorials and then create a pull request that will be reviewed by our team to potentially add your content. Follow [these intructions on how to create a pull request in GitHub](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request).

Added content will only be accepted if it follows these guidlines:

- For Jupyter Notebook Tutorials, follow [this template](../notebooks/Tutorials_TEMPLATE.ipynb) as a standard.
- For tutorials outside of Jupyter Notebooks, the format must have the following sections: `add sections from above template`
- The tutorial must be tested successfully and reviewed by a PO.DAAC member non-author. (This will be done before merging the pull request.)

## Instructions for PO.DAAC Contributors *- in progress, coming soon*

#### Cookbook Structure
 - How Quarto Works
 
#### How to Add/Edit Written Cookbook Content
 - Tips for previewing! add quarto preview instructions
 - format for Dataset Specific Examples

#### How to Add Tutorials

Adding tutorials as a PO.DAAC Contributor should follow the same instructions as those outside of PO.DAAC. See [above](Contribute.qmd#make-suggestions-or-add-tutorials).

## Questions about the contribute process? 

Create an issue on our [tutorials Issues GitHub page](https://github.com/podaac/tutorials/issues).

