---
title: ECCO
subtitle: Data Tutorials 
---

## Background

The Estimating the Circulation and Climate of the Ocean (ECCO) project makes the best possible estimates of ocean circulation and its role in climate. ECCO combines state-of-the-art ocean circulation models with global ocean data sets.
More information can be found on [PO.DAAC's ECCO webpage](https://podaac.jpl.nasa.gov/ECCO).

## Data Resources & Tutorials

### Data Access

#### In-cloud - [Direct Access to ECCO V4r4 Datasets in the Cloud](../external/ECCO_cloud_direct_access_s3.ipynb)

In this notebook, you will learn to 1) identify Amazon Web Services (AWS) S3 endpoints corresponding to two ECCO datasets of interest, 2) retrieve your AWS credentials which provide access to PO.DAAC data in AWS, 3) load the target netCDF files into two multi-file datasets with xarray, and 4) slice and plot the datasets as animated time series using matplotlib and cartopy. The notebook finishes by writing the animations to disk as MP4 files. The two variables analyzed in this example are global monthly sea surface height (SSH) data and monthly ocean temperature flux (TFLUX) data over the Gulf of Mexico. 

#### Local Machine Download - [Access to ECCO V4r4 Datasets on a Local Machine](../external/ECCO_download_data.ipynb)

This is a modified version of the In-cloud Access python notebook above to batch download ECCO data on a local machine.

### Use Case Demo

#### [ECCO Science Use Case Jupyter Notebook Demonstration](../notebooks/meetings_workshops/workshop_osm_2022/ECCO_ssh_sst_corr.ipynb)

This tutorial will use data from the ECCO model to derive spatial correlations between sea surface temperature anomaly and sea surface height anomaly through time for two regions of the Indian Ocean. The goal is to investigate the correlative characteristics of the Indian Ocean Dipole and how the east and west regions behave differently. 


## Additional Resources

[ECCO Project Website](https://ecco-group.org/home.cgi)

[Data in Action: Unveiling small-scale ocean circulation through high-resolution Sea Surface Height](https://podaac.jpl.nasa.gov/DataAction-2023-09-15-Unveiling-small-scale-ocean-circulation-through-high-resolution-Sea-Surface-Height)