---
title: GHRSST
subtitle: Data Tutorials 
---

## Background

The Group for High Resolution Sea Surface Temperature (GHRSST) was established in 2002 to foster an international focus and coordination for the development of a new generation of global, multi-sensor, high-resolution near real time SST datasets. It brings together international space agencies, research institutes, universities, and government agencies to collectively address the scientific, logistical and managerial challenges posed by creating the SST datasets and services within the Project. The overall aim of the GHRSST is to provide the best quality sea surface temperature data for applications in short, medium and decadal/climate time scales in the most cost effective and efficient manner through international collaboration and scientific innovation.
More information can be found on [PO.DAAC's GHRSST webpage](https://podaac.jpl.nasa.gov/GHRSST).

## Data Resources & Tutorials

#### [Mapping Sea Surface Temperature Anomalies to Observe Potential El Niño Conditions](../notebooks/datasets/enso_MUR_tutorial_final.ipynb) - Utilizes the PO.DAAC Data Downloader to download SSTA from the GHRSST MUR climatology dataset and plot on a local machine.

#### [QGIS - Mapping Sea Surface Temperature Anomalies](../notebooks/GIS/MUR_SSTA_QGIS.md) - how to visualize and project SSTA in QGIS.

#### [Using OPeNDAP to Access the MUR Sea Surface Temperature dataset](../notebooks/opendap/MUR-OPeNDAP.ipynb) - opening and visualizing the GHRSST MUR SST dataset using OPeNDAP.

#### [MUR Sea Surface Temperature Analysis of Washington State](../notebooks/datasets/MUR_SST_Washington_Comparison.ipynb) - Using earthaccess to open GHRSST MUR SST dataset in the cloud over Washington State.

## Additional Resources

[GHRSST Project Page](https://www.ghrsst.org/)
