---
title: GIS
subtitle: StoryMaps and Tutorials using Geographic Information Systems (GIS)
---

## **NASA Earthdata GIS (EGIS)**

- SWOT HR Level 2 River Single-Pass Vector Data Product GIS services available via [NASA Earhtdata GIS (EGIS)](https://gis.earthdata.nasa.gov/portal/home/index.html) 
- [SWOT Level 2 River Single-Pass Vector Data Product GIS services](../notebooks/GIS/SWOT_Rivers_EGIS_Services.md)
- [SWOT Rivers EGIS Access Guide](../notebooks/GIS/SWOT_EGIS_access.ipynb)
- [SWOT Rivers EGIS Python Guide](../notebooks/GIS/SWOT_EGIS_access_Python.ipynb)

## **GIS StoryMaps of Select Datasets:**

#### [**PO.DAAC GIS StoryMap Collection Page**](https://storymaps.arcgis.com/collections/413c17cba4b44be18e445c1caaf03fff)

- [Exploring Water Surface Extent with Satellite Data](https://storymaps.arcgis.com/collections/413c17cba4b44be18e445c1caaf03fff?item=1)
- [SWOT: Through a GIS Lens](https://storymaps.arcgis.com/collections/413c17cba4b44be18e445c1caaf03fff?item=2)
- [Utilizing GRACE data over the Colorado River Basin](https://storymaps.arcgis.com/collections/413c17cba4b44be18e445c1caaf03fff?item=3)
- [The Oceans & Melting Glaciers: OMG & GRACE](https://storymaps.arcgis.com/collections/413c17cba4b44be18e445c1caaf03fff?item=4)

## **GIS Walkthroughs**

- [Mapping Sea Surface Temperature Anomalies in QGIS](../notebooks/GIS/MUR_SSTA_QGIS.md)
- [Transform SWOT Datetime field for use in GIS](../notebooks/GIS/SWOT_datetime_GIS.ipynb)

## **GIS Jupyter Notebook Tutorials**

- [GIS SWOT shapefile exploration](../notebooks/GIS/SWOT_GISshapefiles.ipynb)
- NetCDF to Geotiff Conversion: SWOT Data Example - [mac or Linux](../notebooks/GIS/Subscriber_nc_to_tif_SWOT.qmd) | [Windows](../notebooks/GIS/GDAL_NetCDF_GeoTIFF.ipynb)
- OPERA DSWx-HLS access & mosaic visualization - [in the cloud](../notebooks/datasets/OPERA_GIS_Cloud.ipynb) | [locally](../notebooks/datasets/OPERA_GIS_Notebook.ipynb)
