---
title: "PO.DAAC Cookbook"
subtitle: "Making complex data simple with a few helpful tutorials"
---

## Welcome {#welcome}

Welcome to the tutorial repository for the Physical Oceanography Distributed Active Archive Center ([PO.DAAC](https://podaac.jpl.nasa.gov/))! Our goal is to make NASA’s ocean, climate, and surface water data universally accessible and meaningful.

*This site is under active, open development. Stay tuned for more and ever-evolving content!*


## About the Cookbook

The PO.DAAC Cookbook is a place to learn about & experiment with the NASA Earthdata datasets we host. All data can be accessed freely in the cloud or downloaded locally. The **How To** section gives bite-sized pieces of code created in collaboration with the [NASA Earthdata Cloud Cookbook](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/) community. **Tutorials** connect these pieces together to form example workflows specific to PO.DAAC datasets both within the cloud and on a local machine. To learn more about the cloud specifically, see the [Earthdata Cloud Primer](https://earthdata.nasa.gov/learn/user-resources/webinars-and-tutorials/cloud-primer.) 

Most tutorials included in this cookbook are created with Python Jupyter Notebooks. All chapters in the cookbook are a combination of narrative, links, code, and outputs — and underlying each chapter is a file type that you can access on [PO.DAAC GitHub](https://github.com/podaac/tutorials) (linked on the left navbar and right margin of each page): Jupyter (.ipynb) or Quarto (.qmd) files.

## About PO.DAAC

The Physical Oceanography Distributed Active Archive Center (PO.DAAC) is a NASA Earth Observing System Data and Information System ([EOSDIS](https://www.earthdata.nasa.gov/eosdis)) data center managed by the Earth Science Data and Information System ([ESDIS](https://www.earthdata.nasa.gov/esds)) Project. The PO.DAAC is operated by Jet Propulsion Laboratory (JPL) in Pasadena, California.
