---
title: OPERA
subtitle: Data Tutorials 
---

## Background

The Observational Products for End-Users from Remote Sensing Analysis (OPERA) product suite is designed to collect data from satellite radar and optical instruments to generate three products:

- a near-global Dynamic Surface Water Extent (DSWx) product suite
- a near-global land-surface Disturbance (DIST) product suite
- a North America land-surface Displacement (DISP) product suite

Only DSWx products will be distributed through PO.DAAC. More information can be found on [PO.DAAC's OPERA webpage](https://podaac.jpl.nasa.gov/OPERA).

## Data Resources & Tutorials

### Imagery Exploration

[Surface Water Extent Worldview StoryMap](https://worldview.earthdata.nasa.gov/?l=Coastlines_15m,Reference_Features_15m,Reference_Labels_15m,OPERA_L3_Dynamic_Surface_Water_Extent-HLS_Provisional(disabled=5),Land_Water_Map&lg=true&tr=surface_water_extent&t=2023-09-16-T00%3A00%3A00Z)

[SOTO by Worldview](https://soto.podaac.earthdatacloud.nasa.gov/) - explore OPERA imagery in a GUI

[Video Tutorial: Exploring OPERA Surface Water Extent Data in NASA Worldview](https://www.youtube.com/watch?v=0JeF_okiKmU)

### Search & Download

**Via Graphical User Interface:**

Find/download [OPERA data on Earthdata Search](https://search.earthdata.nasa.gov/search?q=opera_L3)

**Via Command Line** - PO.DAAC subscriber/downloader example: 

``` bash
podaac-data-subscriber -c OPERA_L3_DSWX-HLS_PROVISIONAL_V1 -d ./data/OPERA_L3_DSWX-HLS_PROVISIONAL_V1 --start-date 2023-04-04T00:00:00Z -e .tif
```

> See [how to Download/Subscribe](DataSubscriberDownloader.qmd) for more information on how to use the PO.DAAC subscriber/downloader.

### Workflow tutorials: Access & Visualization

[AWS Cloud: OPERA Dynamic Surface Water Extent (DSWx) Data](../notebooks/datasets/OPERA_GIS_Cloud.ipynb) - How to search for, access, visualize, and mosaic OPERA data over lake Powell while working in the cloud.

[Local Machine: OPERA Dynamic Surface Water Extent (DSWx) Data](../notebooks/datasets/OPERA_GIS_Notebook.ipynb) - How to search for, download, visualize, and mosaic OPERA data over lake Powell while working on a local machine.

### GIS workflows

[StoryMap: Exploring Water Surface Extent with Satellite Data](https://storymaps.arcgis.com/collections/413c17cba4b44be18e445c1caaf03fff?item=1)

[OPERA ArcGIS Toolbox](https://github.com/OPERA-Cal-Val/OPERA-ArcGIS-Toolbox/tree/main) - GitHub repository with three geoprocessing tools: OPERA Granule Download, OPERA Granule Filter, and OPERA Raster Mosaic

## Additional Resources

[OPERA Applications GitHub Notebooks](https://github.com/OPERA-Cal-Val/OPERA_Applications/tree/main) - check out the [leafmap examples](https://github.com/OPERA-Cal-Val/OPERA_Applications/tree/main/leafmap)!

[NASA Mission Page](https://www.jpl.nasa.gov/go/opera)
