---
title: Workflows with Multiple Datasets
---
## Multiple Cloud Datasets

### Example: Salinity Ocean Satellite & In-situ Comparison 

This tutorial compares salinity from the SMAP satellite and Saildrone in-situ measurements. Both datasets are located within the cloud.

[Monitoring Changes in the Arctic Using Saildrone and SMAP Satellite](../notebooks/meetings_workshops/arctic_2019.ipynb)

### Example: Amazon Estuary Exploration

This tutorial explores the relationships between land water equivalent thickness, river height, sea surface salinity, and sea surface temperature in the Amazon River estuary and coastal region from multiple datasets (GRACE-FO, Pre-SWOT MEaSUREs, OISSS, & MODIS).

[Amazon Estuary Exploration: In AWS Cloud Version](../notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb)

## Pairing Cloud and Non-cloud Data 

*Tutorials highlighting workflows that utilize both cloud and non-cloud data simultaneously.*

### Example: River Heights Comparison

This tutorial explores the relationships between satellite and in situ river heights in the Mississippi River using Pre-SWOT MEaSUREs and USGS river height gauges.

[Mississippi River Heights Exploration: Working with In Situ Measurements and Satellite Hydrology Data in the Cloud](../notebooks/meetings_workshops/swot_ea_hackweek_2022/River_Heights_in_the_Cloud.ipynb)

### Example: Sea Surface Temperature Ocean Satellite & In-situ Comparison

This tutorial co-locates in-situ measurements and satellite data of sea surface temperature (SST) near the European coast for cross-validation of data or model validation. Datasets: Argo floats, MODIS-Aqua L2 SST, & MUR L4 SST.

[Use Case: Co-locate satellite and in-situ data for cross-validation](../notebooks/SWOT-EA-2021/Colocate_satellite_insitu_ocean.ipynb) - *Undergoing updates shortly*


