---
title: Science Data Stories
---

### **Hurricane Helene Sea Surface Temperature and Sea Surface Height** - [Tutorial](../notebooks/DataStories/HurricaneHelene_SST_SSH_Notebook.ipynb)
*Use Python to plot the SST and SSH in the Gulf of Mexico to show how Hurricane Helene impacted the region in September 2024.*

### **Amazon Estuary Exploration** - [Tutorial - Cloud](../notebooks/meetings_workshops/workshop_osm_2022/CloudAWS_AmazonRiver_Estuary_Exploration.ipynb) | [Tutorial - Local](../notebooks/meetings_workshops/workshop_osm_2022/Cloud_DirectDownload_AmazonRiver_Estuary_Exploration.ipynb)
*Explores the relationships between land water equivalent thickness, river height, sea surface salinity, and sea surface temperature in the Amazon River estuary and coastal region from multiple datasets (GRACE-FO, Pre-SWOT MEaSUREs, OISSS, & MODIS).*

### **EOF Decomposition of Global Monthly SST** - [Tutorial](../notebooks/DataStories/eof_example_ersst.ipynb)
*This demo uses the xeofs package to replicate part of an empirical orthogonal function (EOF) analysis on century-long, global sea surface temperatures (SSTs) published in Journal of Climate (Messie and Chavez, 2011): https://doi.org/10.1175/2011JCLI3941.1, and can be run entirely in the cloud.*

### **Salinity Ocean Satellite & In-situ Comparison** - [Tutorial](../notebooks/meetings_workshops/arctic_2019.ipynb)
*Monitoring Changes in the Arctic Using Saildrone (in situ) and SMAP (satellite), comparing salinity. Both datasets are located within the cloud.*

## Pairing Cloud and Non-cloud Data 

*Tutorials highlighting workflows that utilize both cloud and non-cloud data simultaneously.*

### **Mississippi River Heights Exploration** - [Tutorial](../notebooks/meetings_workshops/swot_ea_hackweek_2022/River_Heights_in_the_Cloud.ipynb)
*This tutorial explores the relationships between satellite and in situ river heights in the Mississippi River using Pre-SWOT MEaSUREs and USGS river height gauges within the cloud.*

### **Sea Surface Temperature Ocean Satellite & In-situ Comparison** - [Tutorial](../notebooks/SWOT-EA-2021/Colocate_satellite_insitu_ocean.ipynb)
*This tutorial co-locates in-situ measurements and satellite data of sea surface temperature (SST) near the European coast for cross-validation of data or model validation. Datasets: Argo floats, MODIS-Aqua L2 SST, & MUR L4 SST.*

