---
title: Sentinel-6 Michael Freilich
subtitle: Data Tutorials 
---

## Background

The Sentinel-6 Michael Freilich satellite measures the height of the ocean. In addition, an instrument on board the satellite uses the Global Navigation Satellite System Radio-Occultation sounding technique, which analyses changes in signals from international global navigation system satellites to determine atmospheric temperature and humidity.
More information can be found on [PO.DAAC's Sentinel-6 Michael Freilich webpage](https://podaac.jpl.nasa.gov/Sentinel-6).

## Data Resources & Tutorials

### Data Access

- [Access in Cloud](../notebooks/sentinel-6/S6_Cloud_Notebook.ipynb)  
- [Access by Cycle/Pass](../notebooks/sentinel-6/Access_Sentinel6_By_CyclePass.ipynb)          
- [Access Near Real-Time Data](../notebooks/sentinel-6/Access_Sentinel6_NRT.ipynb)          
- [OPeNDAP Access](../notebooks/meetings_workshops/workshop_osm_2022/S6_OPeNDAP_Access_Gridding.ipynb)


## Additional Resources

[NASA Mission Page](https://www.jpl.nasa.gov/missions/sentinel-6)
