---
title: SMAP
subtitle: Data Tutorials 
---

## Background

The Soil Moisture Active Passive (SMAP) satellite is designed to principally measure soil moisture and freeze/thaw state from space for all non-liquid water surfaces globally within the top layer of the Earth. The mission additionally provides a value-added Level 4 terrestrial carbon dataset derived from SMAP observations.
More information can be found on [PO.DAAC's SMAP webpage](https://podaac.jpl.nasa.gov/SMAP).

## Data Resources & Tutorials

#### [Visualizing Ocean Salinity as Powerful Storms Wreak Havoc in California](../notebooks/datasets/smap_imerg_tutorial.ipynb) - Data in Action Use Case Notebook Tutorial with a local machine workflow

- [The Data in Action Story](https://podaac.jpl.nasa.gov/DataAction-2022-03-01-SMAP-Visualizing-Ocean-Salinity-as-Powerful-Storms-Wreak-Havoc-in-California)

#### [Monitoring Changes in the Arctic Using SMAP Satellite data and Saildrone](../notebooks/meetings_workshops/arctic_2019.ipynb) - AWS cloud tutorial that compares salinity from the SMAP satellite and Saildrone in-situ measurements


## Additional Resources

[NASA Mission Page](https://smap.jpl.nasa.gov/)

[Data in Action: Using Coastal Surface Salinity to Monitor Global Water Cycle Changes](https://podaac.jpl.nasa.gov/DataAction-2024-04-18-Using-Coastal-Surface-Salinity-to-Monitor-Global-Water-Cycle-Changes)