---
title: S-MODE
subtitle: Data Tutorials 
---

## Background

The Submesoscale Ocean Dynamics and Vertical Transport Experiment (S-MODE) is a NASA Earth Venture Suborbital (EVS-3) mission that utilizes research aircraft equipped with state-of-the-art remote sensing instruments, a research vessel, Wave Gliders, Saildrones, and many other in situ assets. These instruments contribute to an unprecedented view of the physics of submesoscale eddies and fronts, and their effects on vertical transport in the upper ocean. The S-MODE investigation is composed of a Pilot Campaign (Fall 2021) and two Intensive Operating Periods (IOP-1 and IOP-2, Fall 2022 and Spring 2023). Each field campaign is between 3-4 weeks in duration. The scientific area of interest is located about 150 miles off the coast of San Francisco

More information can be found on [PO.DAAC's SMODE webpage](https://podaac.jpl.nasa.gov/S-MODE).

## Data Resources & Tutorials

### Science Case Study Airborne
The [DownloadDopplerScattData.ipynb](../external/DownloadDopplerScattData.ipynb) notebook walks through creating the .netrc file and downloading the Dopplerscatt data used in this case study. The [VisualizeDopplerScattData.ipynb](../external/VisualizeDopplerScattData.ipynb) notebook contains the Airborne Science Case Study data visualization and discussion. Instructions for installing the airborne material in a conda environment are contained in this [Airborne Case Study README](https://github.com/podaac/2022-SMODE-Open-Data-Workshop/blob/main/README-Airborne.md).

### Science Case Study In Situ
The [insitu_dataviz_demo.ipynb](../external/insitu_dataviz_demo.ipynb) notebook contains the In Situ Science Case Study data visualization and discussion. This notebook also contains sample code to run the PO.DAAC Data Downloader to download Saildrone data. Instructions for installing the necessary Python packages, and more information on obtaining S-MODE data are in the [In Situ Case Study README](https://github.com/podaac/2022-SMODE-Open-Data-Workshop/blob/main/README-InSitu.md).


## Additional Resources

### Data in Action Story

[A Closer Look at the Sub-Mesoscale Ocean Dynamics Experiment (S-MODE)](https://podaac.jpl.nasa.gov/DataAction-2023-08-29-A-Closer-Look-at-the-Sub-Mesoscale-Ocean-Dynamics-Experiment-S-MODE)

### 2022 S-MODE Open Data Workshop

[**https://espo.nasa.gov/s-mode/content/S-MODE_2022_Open_Data_Workshop**](https://espo.nasa.gov/s-mode/content/S-MODE_2022_Open_Data_Workshop){.uri} - [Recordings and Presentations](https://espo.nasa.gov/s-mode/content/S-MODE_2022_ODW_Recording_and_Presentations)

The Submesoscale Ocean Dynamics and Vertical Transport Experiment (S-MODE) science team hosted a virtual Open Data Workshop on 1 December 2022 from 11:00am – 1:00pm ET to share about the S-MODE mission, to learn about its instrumentation, and find out how to access and use its data products.

