---
title: Datum Conversion for SWOT Data
subtitle: Community Tutorials
jupyter:
  jupytext:
    text_representation:
      extension: .qmd
      format_name: quarto
      format_version: '1.0'
      jupytext_version: 1.16.1
  kernelspec:
    display_name: Python 3 (ipykernel)
    language: python
    name: python3
---

# Datum Conversion for SWOT Data

Please first see the [SWOT Data User Handbook](https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-docs/web-misc/swot_mission_docs/D-109532_SWOT_UserHandbook_20240502.pdf?_ga=2.76536725.1816513343.1724259518-1354658737.1715875596) sections 3.3.3 on the reference ellipsoid and 11.3.1 on the geoid. In addition, section 3.1.23 gives detailed information about Height with section 3.1.24 elaborating on Sea Surface Height Anomalies and 3.1.25 elaborating on Water Surface Elevation over inland waters.

As a summary, SWOT data is referenced to the WGS84 reference ellipsoid as a first step, and in a second step referenced to the EGM2008 geoid that references WGS84. To get a direct conversion with another dataset, it is easiest to transform all local data to the EGM2008 geoid. We recognize this conversion is different globally and depending on the data being used to compare, but we have collected a few community examples of direct comparisons to share below:

1. Comparing USGS gage data and SWOT data in the United States - [Python Notebook](../notebooks/datasets/SWOT_USGS_Comparison.ipynb)
2. Converting the SWOT Frame and Geoid in Canada - [Google Colab Section from Canadian Colleagues](https://colab.research.google.com/drive/1we0a24gBKbs-CFMVBfRIUm4SSW8RdwmA#scrollTo=cu09EYYRxxd4)

If you have any questions for your specific region, please ask in the [Earthdata Forum](https://forum.earthdata.nasa.gov/viewforum.php?f=7) and experts should be able to help.
