---
title: SWOT
subtitle: SWOT Data Tutorials - Get Started with Sample Data!
---

## SWOT Background

The Surface Water and Ocean Topography (SWOT) mission aims to provide valuable data and information about the world's oceans and its terrestrial surface water such as lakes, rivers, and wetlands. SWOT is being developed jointly by NASA and Centre National D'Etudes Spatiales (CNES), with contributions from the Canadian Space Agency (CSA) and United Kingdom Space Agency (UKSA). The satellite launched on December 16, 2022 and data is expected to be released to the public no earlier than Fall 2023. PO.DAAC is the NASA archive for the SWOT mission, and will be making data available via the NASA Earthdata Cloud (hosted in AWS) with direct download capabilities available. More information can be found on [PO.DAAC's SWOT webpage](https://podaac.jpl.nasa.gov/SWOT).

PO.DAAC will host a variety of [SWOT data products](https://podaac.jpl.nasa.gov/SWOT?tab=datasets). Their product description documents can be found in the chart listing each dataset. Before these SWOT products are available, we have [SWOT simulated datasets](https://podaac.jpl.nasa.gov/SWOT?tab=datasets&sections=about%2Bdata) encompassing both oceanography and hydrology sample data. This data is not for analysis, but rather to become comfortable with future SWOT products data formats and access mechanisms.

## SWOT Data Resources & Tutorials

### Search & Download

#### **Via Graphical User Interface:**

- Find/download [simulated SWOT data on Earthdata Search](https://search.earthdata.nasa.gov/search?q=simulated%20swot)

#### **Programmatically:** ie. within Python code workflows

- [Search and Download via `earthaccess`](../notebooks/SearchDownload_SWOTviaCMR.ipynb)
- [with unique SWORD river reach ID](../notebooks/SWORD_River_Demo.ipynb)
- [with unique Hydrologic Unit Code (HUC) basin ID](../notebooks/HUC Feature Translation Service Examples-updated-20210804.ipynb)

#### **Via Command Line** - PO.DAAC subscriber/downloader examples: 

Hydrology: *These examples will download either the river vector files or the raster files for a location in Texas with multiple passes:* 
``` bash
podaac-data-downloader -c SWOT_SIMULATED_NA_CONTINENT_L2_HR_RiverSP_V1 -d ./SWOT_SIMULATED_NA_CONTINENT_L2_HR_RiverSP_V1 -start-date 2022-08-02T00:00:00Z --end-date 2022-08-22T00:00:00Z -b="-97,32.5,-96.5,33"
```
    
```bash
podaac-data-downloader -c SWOT_SIMULATED_NA_CONTINENT_L2_HR_Raster_V1 -d ./SWOT_SIMULATED_NA_CONTINENT_L2_HR_Raster_V1 --start-date 2022-08-02T00:00:00Z --end-date 2022-08-22T00:00:00Z -b="-97,32.5,-96.5,33"
```

Oceanography: *This example will download modeled sea surface heights:*
    
``` bash
podaac-data-subscriber -c SWOT_SIMULATED_L2_KARIN_SSH_GLORYS_CALVAL_V1 -d ./data/SWOT_SIMULATED_L2_KARIN_SSH_GLORYS_CALVAL_V1 --start-date 2015-12-30T00:00:00Z
```

``` bash
podaac-data-downloader -c SWOT_SIMULATED_L2_NADIR_SSH_ECCO_LLC4320_SCIENCE_V1 -d ./data/SWOT_SIMULATED_L2_NADIR_SSH_ECCO_LLC4320_SCIENCE_V1 --start-date 2011-11-20T00:00:00Z --end-date 2011-11-20T12:00:00Z
```

> See [how to Download/Subscribe](DataSubscriberDownloader.qmd) for more information on how to use the PO.DAAC subscriber/downloader.

#### Tips for SWOT HR Spatial Search

The following shapefiles (27 MB - nominal orbit, 1.3 MB - calibration orbit), when brought into a GIS tool such as ArcGIS or QGIS, can support the user to more easily navigate and identify the tile ID of the SWOT HR L2 PIXC and PIXCVec data products to facilitate easier, more efficient data search. *Note: The horizontal lines that appear within the shapefiles are an artifact of the tile geometries intersecting the international date line; the horizontal lines are to be ignored when identifying tiles.*

##### Download **Tile Boundary Shapefiles** for
- the **full nominal SWOT orbit** by clicking [**here**](https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-docs/web-misc/SWOT/RefOrbitTrackTileCornerCoords/SWOT_RefOrbitTrackTileCornerCoords_Nom_v101.zip) having logged into your [Earthdata Login](https://urs.earthdata.nasa.gov/).
- the **calibration SWOT orbit** by clicking [**here**](https://archive.podaac.earthdata.nasa.gov/podaac-ops-cumulus-docs/web-misc/SWOT/RefOrbitTrackTileCornerCoords/SWOT_RefOrbitTrackTileCornerCoords_Cal_v101.zip) having logged into your [Earthdata Login](https://urs.earthdata.nasa.gov/).

To support spatial search of SWOT HR data products, the following naming conventions may also be of help. *Tip: use these shortname identifiers below when searching for SWOT HR data in the [NASA Earthdata Search portal](https://search.earthdata.nasa.gov/) or programmatically using the CMR API and/or `earthaccess` python library.*

SWOT HR data products use Tiles, Scenes, or Continent-level Swaths IDs depending on the product, which define the spatial extent of what is in each file, as follows in the chart below. Along-track scene and tile numbers are numbered sequentially following the spacecraft flight direction, so the numbers increase from south to north for ascending passes and from north to south for descending passes.

| Product (organized by…)                             | File Naming  Convention | Notes                                                                                                                                                                                                                                                                                                                                           |   |   |
|-----------------------------------------------------|-------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---|---|
| L2_HR_RiverSP <br /> L2_HR_LakeSP <br />(continent-level swaths) | PPP_CC                  | PPP = pass number (valid range: 001-584) <br /> CC = continent code (options listed below) <br /><br /> AF - Africa <br /> EU - Europe and Middle East <br /> SI - Siberia <br /> AS - Central and Southeast Asia <br /> AU - Australia and Oceania <br /> SA - South America  <br /> NA - North America and Caribbean <br /> AR - North American Arctic <br /> GR - Greenland <br /><br /> *Ex: 013_NA = pass 013, North America* |   |   |
| L2_HR_PIXC <br />L2_HR_PIXCVec<br /> L1B_HR_SLC <br />(tiles)         | PPP_TTTC                | PPP = pass number (valid range: 001-584) <br /> TTT = tile number (valid range: 001-308) <br /> C = character L or R corresponding to left or right swaths <br /><br /> *Ex: 001_120R = pass 001, right swath, tile 120*                                                                                                                                                  |   |   |
| L2_HR_Raster<br /> (scenes)                               | PPP_SSS                 | PPP = pass number (valid range: 001-584) <br /> SSS = scene number (valid range: 001-154)   <br /><br /> Scenes correspond to 2 x 2 sets of tiles <br /> **scene number x 2 = tile number** <br /><br /> *Ex: 001_060 = pass 001, scene 60, corresponding to the same location as the PIXC/PIXCVec tile example above.*                                                               |   |   |

In [Earthdata Search GUI](https://search.earthdata.nasa.gov/search):

1. Use the top left Search Box and search with keywords, e.g. SWOT L2 HR 
2. Select a collection of interest
3. A Filter Granule filtering capability will show up on the left hand side of the GUI. Recall naming convention is `_cycle_pass_spatialIdentifier_`. 
    - Use **wildcards** to narrow down spatially, using one of the codes from the table above depending on your use case. *Tip: use underscores ( _ ) with your wildcard key words for a more specific search.*
    - Example: `*_NA_*` will filter the RiverSP or LakeSP collection selected to only return those granules (files) that are part of the North America collection
    - Example: `*_004_256_*` will filter the RiverSP or LakeSP collection selected to only return those granules (files) that correspond to cycle 004, pass 256
    - Example: `*_004_253_128*` will filter the Raster collection selected to only return those granules (files) that correspond to cycle 004, pass 253, scene 128
4. In addition, you can also draw a **region of interest (ROI)** on the map, using the Spatial Search Filter icon or the Advanced Search under the main search box. These will help to filter what is returned for the spatial search. *Tip: It is recommended that ROI searches are used together with wildcards described above for a more accurate search.*
 

### In-cloud Access & Visualization

[Access sample SWOT Hydrology data in the cloud](../notebooks/meetings_workshops/swot_ea_workshop_sept2022/SWOTHR_s3Access.ipynb)

[Access sample SWOT Oceanography data in the cloud](../external/Direct_Access_SWOT_sim_Oceanography.ipynb)

### GIS workflows

[SWOT: Through a GIS Lens StoryMap](https://storymaps.arcgis.com/stories/4a9184e813e540248040069580f6a54c)

[Shapefile exploration](../notebooks/GIS/SWOTsample_GISshapefiles.ipynb)

### Transform

[Transform SWOT Hydrology river reach shapefiles into time series](../notebooks/GIS/SWOTsample_CSVconversion.ipynb) 

[NetCDF to Geotiff Conversion](../notebooks/GIS/Subscriber_nc_to_tif_SWOT.qmd)

## Additional Resources

### 2022 SWOT Ocean Cloud Workshop

[**https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/**](https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/){.uri}

The goal of the workshop was to enable the (oceanography) science team to be ready for processing and handling the large volumes of SWOT SSH data in the cloud. Learning objectives focus on how to access the [simulated SWOT L2 SSH data](https://podaac.jpl.nasa.gov/announcements/2022-01-31-Release-simulated-SWOT-SSH-version1-datasets) from Earthdata Cloud either by downloading or accessing the data on the cloud.