---
title: Tech Guides
---

## Cloning this GitHub Repository

Cloning the podaac/tutorials repository allows you to have a copy of all the PO.DAAC Cookbook Notebook tutorials on your own machine to use. Follow [these instructions to clone our repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository) from GitHub documentation, selecting your machine type and what method you would like to use to clone at the top ([GitHub Desktop](https://desktop.github.com/) is a useful interface if you would rather not use the command line). 

The link for this particular repository is: https://github.com/podaac/tutorials.git
In the command line or Git Bash change the working directory to the location where you would want the cloned directory and then type:
``` bash
$ git clone https://github.com/podaac/tutorials
```

## Tech How To's & Useful Introductions

- [How to Set Up an EC2 Instance](../external/July_2022_Earthdata_Webinar.ipynb) - Earthdata Webinar outlining how to set up your own AWS cloud computer, an Elastic Computer Cloud (EC2)
- [NASA `earthaccess`](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/tutorials/earthaccess-demo.html) - a Python package to search, preview and access NASA datasets (on-prem or in the cloud) with a few lines of code
- [Get started with GitHub](https://docs.github.com/en/get-started/quickstart/hello-world) - develop and share code in a collaborative environment
- [Introduction to Xarray](../external/Introduction_to_xarray.ipynb) - A useful Python Package while working with NASA Earthdata
- [Jupyter Lab](https://jupyter.org/install), [RStudio Desktop](https://posit.co/download/rstudio-desktop/), or [Visual Studio Code](https://code.visualstudio.com/) - useful coding workspaces
- [How to scale your NASA data workflows on the cloud, in parallel - a Coiled example](https://nasa-openscapes.github.io/news/2023-11-07-coiled-openscapes/index.html) - Guide for NASA Cloud computing at scale. How to run existing NASA data workflows on the cloud, in parallel, with minimal code changes using Coiled. (_Reference herein to any specific commercial product, process, or service by trade name, trademark, manufacturer, or otherwise, does not constitute or imply its endorsement by the United States Government or the Jet Propulsion Laboratory, California Institute of Technology._)

## A Growing List of Resources 
- [NASA Earthdata Cloud Cookbook](https://nasa-openscapes.github.io/earthdata-cloud-cookbook/) - Tutorials & data recipes applicable to all NASA datasets
- [NASA Earthdata: How to Cloud](https://earthdata.nasa.gov/learn/user-resources/webinars-and-tutorials/how-to-cloud-for-earth-scientists)
- [NASA Earthdata Cloud Primer](https://earthdata.nasa.gov/learn/user-resources/webinars-and-tutorials/cloud-primer) - AWS cloud primer: helpful tutorials for how to set up your own EC2 cloud instance in AWS, attach storage, move files back and forth, and more.
- [Setting up Jupyter Notebooks in a user EC2 instance in AWS](https://medium.com/@alexjsanchez/python-3-notebooks-on-aws-ec2-in-15-mostly-easy-steps-2ec5e662c6c6) - helpful blog post for setting up jupyter notebooks in an EC2 instance in AWS. (Builds on the Cloud Primer tutorials, which are missing that next step)
- [Running the NASA Cloud Workshop notebooks with mybinder.org](https://github.com/eeholmes/jupyterhub) - by Eli Holmes, 2021 Cloud Hackathon Participant who then set up working in Binder
- [Cloud Optimized Geospatial Formats Guide](https://developmentseed.org/cloud-optimized-geospatial-formats-guide/) - Methods for Generating and Testing Cloud-Optimized Geospatial Formats
