---
title: Webinars
---

**2024:** [**Accessing Data for the World's Water with SWOT**](https://www.earthdata.nasa.gov/learn/webinars-and-tutorials/webinar-podaac-2024-03-20) - Learn how to discover, access, and use Surface Water and Ocean Topography (SWOT) mission data and how these data can lead to new, innovative science and applications in the world of water.

**2023:** [**From Ocean to Cloud—Enabling Workflows and Data Utilization**](https://www.earthdata.nasa.gov/learn/webinars-and-tutorials/webinar-podaac-2023-08-23) - This webinar describes how to set up and use cloud services to run analyses on physical oceanography data at NASA's PO.DAAC.

**2022:** [**Moving Code to the Data: Analyzing Sea Level Rise Using Earth Data in the Cloud**](https://www.earthdata.nasa.gov/learn/webinars-and-tutorials/webinar-cloud-computing-PO.DAAC) - How in-cloud analysis can be achieved with minimal knowledge of AWS cloud walking through a [Jupyter Notebook tutorial](../external/July_2022_Earthdata_Webinar.ipynb).

**2021:** [**Surfing Ocean Data in the Cloud**](https://podaac.jpl.nasa.gov/animations/Webinar_Surfing_Ocean_Data_in_the_Cloud_Beginners_Guide_PO.DAAC_NASA_Earthdata_Cloud) - The Beginner's Guide to PO.DAAC in the NASA Earthdata Cloud.

**2020:** [**Making Waves: PO.DAAC’s Journey from Servers to a Cloud Environment**](https://podaac.jpl.nasa.gov/animations/Webinar-Making-Waves:PODAAC-Journey-from-Servers-to-Cloud-Environment) - Our move to the cloud, what it means for the data, services, and resources PO.DAAC provides, and what it means for the data user community. 