---
title: Workshops
---

We develop tutorials for teaching events that each have their own e-book. We often do this in collaboration with [NASA OpenScapes](https://nasa-openscapes.github.io/). Tutorials are developed to teach open science and Cloud workflows for specific audiences. They are a snapshot in time as workflows with NASA Earthdata Cloud emerge and evolve.

## 2024 SWOT Early Career Researcher Workshop Using Binder

[https://github.com/podaac/2024-SWOT-ECR-Workshop](https://github.com/podaac/2024-SWOT-ECR-Workshop)

Explore SWOT data on a Binder virtual environment or local machine. This material was presented at the 9th Global Energy and Water Exchanges (GEWEX) Open Science Conference and the Hacking Limnology 2024 Virtual Summit Remote Sensing Day. Follow along with the [recording here](https://www.youtube.com/watch?v=7qqiUqR43_8&list=PLDWiCz1Ka4kRhE-g39HwvvyMLtn87m1vH&index=4).

## 2024 SWOT Data Access Workshop

[https://podaac.github.io/2024-SWOT-Hydro-Workshop/](https://podaac.github.io/2024-SWOT-Hydro-Workshop/)

The Surface Water and Ocean Topography (SWOT) satellite, a joint NASA-CNES venture, provides unprecedented measurements of surface water extents and elevations for hydrologic science and applications. This workshop focuses on the SWOT Hydrology datasets including river and lake vector data in shapefiles, and raster, pixel cloud, and pixel vector data in netCDF. In this pre-meeting workshop for the AGU Chapman: Remote Sensing of the Water Cycle Conference, participants are introduced to SWOT and the various ways to access and utilize its data products, including via cloud computing, local download, and data transformation tools.

## 2023 AGU Cloud Workshop

[https://nasa-openscapes.github.io/2023-Cloud-Workshop-AGU/](https://nasa-openscapes.github.io/2023-Cloud-Workshop-AGU/)

In this workshop, NASA Openscapes Mentors from NASA’s Earth Observing System Data and Information System (EOSDIS) DAACs (data centers) teach the foundations of an open science mindset and apply these concepts to work in the cloud with NASA Earthdata. Participants take part in hands-on tutorials using a JupyterHub managed by 2i2c in AWS. The goal is to teach participants how to leverage data and services from NASA Earthdata Cloud within their work across a variety of disciplines and data types, as well as how to apply the concepts of open science as a daily practice. 

## 2022 S-MODE Open Data Workshop

[**https://espo.nasa.gov/s-mode/content/S-MODE_2022_Open_Data_Workshop**](https://espo.nasa.gov/s-mode/content/S-MODE_2022_Open_Data_Workshop){.uri} - [Recordings and Presentations](https://espo.nasa.gov/s-mode/content/S-MODE_2022_ODW_Recording_and_Presentations) - [Github tutorials](https://github.com/podaac/2022-SMODE-Open-Data-Workshop)

The Submesoscale Ocean Dynamics and Vertical Transport Experiment (S-MODE) science team is hosted a virtual Open Data Workshop on 1 December 2022 from 11:00am – 1:00pm ET to share about the S-MODE mission, to learn about its instrumentation, and find out how to access and use its data products.

## 2022 SWOT Ocean Cloud Workshop

[**https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/**](https://podaac.github.io/2022-SWOT-Ocean-Cloud-Workshop/){.uri}

The goal of the workshop is to get ready for Surface Water and Ocean Topography ([SWOT](https://swot.jpl.nasa.gov/)) and enable the (oceanography) science team to be ready for processing and handling the large volumes of SWOT SSH data in the cloud. Learning objectives focus on how to access the [simulated SWOT L2 SSH data](https://podaac.jpl.nasa.gov/announcements/2022-01-31-Release-simulated-SWOT-SSH-version1-datasets) from Earthdata Cloud either by downloading or accessing the data on the cloud. PO.DAAC is the NASA archive for the SWOT mission, and once launched will be making data available via the NASA Earthdata Cloud, hosted in AWS.

## 2021 Cloud AGU Workshop

[**https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU**](https://nasa-openscapes.github.io/2021-Cloud-Workshop-AGU){.uri}

The **2021 Cloud Workshop at AGU: Enabling Analysis in the Cloud Using NASA Earth Science Data** is a virtual half-day collaborative open science learning experience aimed at exploring, learning, and promoting effective cloud-based science and applications workflows using NASA Earthdata Cloud data, tools, and services (among others), in support of Earth science data processing and analysis in the era of big data.

## 2021 Cloud Hackathon

[**https://nasa-openscapes.github.io/2021-Cloud-Hackathon**](https://nasa-openscapes.github.io/2021-Cloud-Hackathon){.uri}

The **Cloud Hackathon: Transitioning Earthdata Workflows to the Cloud** is a virtual 5-day (4 hours per day) collaborative open science learning experience aimed at exploring, creating, and promoting effective cloud-based science and applications workflows using NASA Earthdata Cloud data, tools, and services (among others), in support of Earth science data processing and analysis in the era of big data. Its goals are to:

1.  **Introduce** Earth science data users to NASA Earthdata cloud-based data products, tools and services in order to increase awareness and support transition to cloud-based science and applications workflows.

2.  **Enable** science and applications workflows in the cloud that leverage NASA Earth Observations and capabilities (services) from within the NASA Earthdata Cloud, hosted in Amazon Web Services (AWS) cloud, thus increasing NASA Earthdata data utility and meaningfulness for science and applications use cases.

3.  **Foster community engagement** utilizing Earthdata cloud tools and services in support of open science and open data.
